### ISSUE TITLE
Search playlist type

### ISSUE THREAD

**Issue by goldyfruit** [sleepyfran/itunespy#14]
Hi @sleepyfran 

I would like to know if there is  a way to search playlists?

Thanks for this library.

**Comment by sleepyfran** [comment]
Hey @goldyfruit! Sorry for the late response. Do you mean Apple Music playlists? If that's the case then this is not supported, as the iTunes API is purely non-user-oriented and can only retrieve general data about what's on the store, so it doesn't connect in any way with Apple Music.

I think something like [apple-music-python](https://github.com/mpalazzolo/apple-music-python) might help you out with this 😃

**Comment by goldyfruit** [comment]
Hey @sleepyfran, no worries!
Yeah but apple-music-python requires an authentication which I try to avoid.

Thanks!
