### ISSUE TITLE
Not working in Russia

### ISSUE THREAD

**Issue by oifj34f34f** [sleepyfran/itunespy#15]
Due to obvious reasons, Apple has blocked access to the iTunes API in Russia. If anyone requires a workaround, they can replace the values of the variables `base_search_url` and `base_lookup_url` with `https://outermost-profit.000webhostapp.com/search` and `https://outermost-profit.000webhostapp.com/lookup`, respectively, in the `__init__.py` file.

**Comment by sleepyfran** [comment]
Hey, thanks for the contribution, but since I have no way of verifying what's happening in those endpoints I don't feel comfortable having this officially announced here. Redacted the URLs, please feel free to fork the project with these changes so that folks can choose to consume that.
