### ISSUE TITLE
Way to search by ISRC?

### ISSUE THREAD

**Issue by kylesurowiec** [sleepyfran/itunespy#5]
I'm using the Spotify and iTunes API together and need a way to guarantee the results returned from each are the same. I haven't found a way to search by ISRC with your wrapper but maybe I missed something.

**Comment by sleepyfran** [comment]
Hey! As far as I know there’s no way to do this with the iTunes Search API, which is the one that this wrapper uses, or at least it’s not documented. Try to open this: https://itunes.apple.com/lookup?isrc={ISRCCode} with a valid ISRC code and see if it returns the result you expect; if so this is an undocumented feature that we can implement in the wrapper, if not then there’s no such feature in the iTunes API.

I saw however a feature like the one you described in the Apple Music API which features a complete different API than the one used by this wrapper but maybe it fits your needs better.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kylesurowiec** [comment]
@sleepyfran Thanks for the response. It looks like the feature I'm looking for only exists in the enterprise version of the iTunes API and the Apple Music API like you mentioned.
