### ISSUE TITLE
Possible to to download movies ?

### ISSUE THREAD

**Issue by dualriposte** [sleepyfran/itunespy#7]
is it possible to download movies that  i bought with python and sync it with the library ? iTunes produce horrible speeds ..i tried with IDM but that don't work bcs i can't play the file maybe library sync issue .

**Comment by sleepyfran** [comment]
Hi! What’s your use case with itunespy in this case? As far as I known there’s no way to download movies through this API since there’s no authentication.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dualriposte** [comment]
Thanks for the reply ...the thing is download speed with iTunes is very maybe that is itunes.exe limitation that's why i wanted to know if it was possible to download movies or songs with a python based downloader so that i can play it with itunes offline

**Comment by sleepyfran** [comment]
As far as I know there's no way to do it through this API, since you can only retrieve public resources and not things that require authentication. Good luck with your search, though!
